language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/kana/vim-textobj-user/

script: |
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=vim-textobj-user
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  VIMRC) -c 'Vader! test/*' > /dev/null

sudo: false
